apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-service
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    MATRIX_API_TOKEN: AgCYOpprZqdb6R34LYZyRIr4vcxuy5XRu9s/IAhnxbOBb4r05fDrDOqvcqXwZBBzQrIrVFEgfs2NHW8528rRYAVkq0nhU6Gs1XfnjgIJrsqetyX1zehPy17g1IBtQVKCt0C071Gq9UtC85tRD1TY24p0AnLax0FmSRk6wo5mKnrrIR0JYdMWdYjYXgONw1VvJm/Lh55AoQodJC7d8mXOjkRr969Dl16W50blx+rUBTCTk4NOueVq/Nt4IET7M7IV6O4v7xRLeEqcELGJLBdgUuEX3as9VFeOiVhcGOyP5WzPQAin4YNTvrot2QZtYHzHvq3X3cV6z4YyeF/w2S8BXOvAqr6KmouWNX7WmqmUXGmm8Txbf+f4gEljnQpSU7NxXlcEM6MJIYHTDntAq4T3AExxTJ3HC09Ge5B5r3+8iLnVkGdO8ULCao04VWXTRlaoM6/T4e9nMwoBHXE3GN1kS8+TOXmVeXyeggVN1FSq1RiHhDfLtDLLz7skXLesXguRCgQ782NtIkAJBU+wspR4kfC3EQ/bA3A27I4xt4wHI+FxdWKEgACUJQCfalpuU2aRhRut36mJTlqU7hfNDZt4hJDmAlJfXc8NjpGkIL7erzqR3YRRMUzq5NMBKrwHoX1e9BFU6flzFqh0y1VNrDq13P/m9ExcUNS+yw9E+wFoKU/LjJJs88M2JqjIhVvBYXO+EtdE9luV1UqB9vtP+A6tiTPmT5tvXPrZDKvzP5xCgKoqZpAC1U9UivtPtysudIPwt3x9vu1M
  template:
    metadata:
      creationTimestamp: null
      name: notification-service
      namespace: monitoring