apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-service
  namespace: monitoring
spec:
  encryptedData:
    MATRIX_API_TOKEN: AgCLWjtkqM7FxeHtYOir/SzSHZE7MUTs2F9ijRBn+MGM1jZ4jXSqIy0+cepikYNnGLdp0MGJq8pC3iJke1mlIVUMemQ4GDF+hOAIpZf38cZc11EvJvgeXYeGvltl+L8sqtD7IgA2wMZRPY75Lw7rGyj+QElav4V/uh/WKZcKQzW2p4hFk1WVPwY7I052ylyN4TyiHw38buI+1zEdWAKz5EXAazCnP/OfFntcC8Yhh59fySto1uMNxRhuwHuS+c1jtgWMENeFv+CvVBOmHnwWCdfxoX4hOWWeo58F71HRCqbYX97UnV4VpcHk6XrQtQYZp9Ht/0lZ/AcKPs3KbGE0cGAVXMdQ0b7Q6Yxyqwi0lCtGP1jFH3JEDq14+KkqCNTHi7s2OmxVl1zNmMzDONamkh1757WbOhmnbsQMHPAdT2xHQ2f7e0TLcHOff/PYaoljdXR1euWyiNpXEd1fznRspQNqGfZXTaG3dIAP/JzQ8bSDun+YOp2Dd4VOa6nqpC06P/TpUsjXwgxTbdPkfoJXS+89OWtzSaAdBJHLaV5NXSVhx4mZgyG8RzNbxSbPcX8ym3ATDwubGeRgC8VVTGZGP/XJINqF4CSurH8jpSOak/ro0oiZvcUKYENpa+nHmD8Z+0Ij7Q9OcnZvSqxDyWxLn1ZmiSVDrRtHxj2wTLMUu2DWEv0SE8HgL42JMAy2939219M1HMAn57EQ4L1czcOPdIOP7GocR867ITHWxZ7Ew498qakw0WbYHlr1
  template:
    metadata:
      creationTimestamp: null
      name: notification-service
      namespace: monitoring