apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "51.2.0"
    chart: kube-prometheus-stack
    plugin:
      env:
        - name: HELM_VALUES
          #TODO - grafana adminSecret should be generated on day-1 and not passed to argocd-sugar plugin due to potential security leaks
          value: |
            crds:
              enabled: true
            coreDns:
              enabled: false
            kubeDns:
              enabled: true
            kubeProxy:
              enabled: false
            kubeScheduler:
              enabled: false
            kubeControllerManager:
              enabled: false
            alertmanager:
              enabled: true
              ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
                  cert-manager.io/cluster-issuer: production
                hosts:
                  - alertmanager.ARGOCD_ENV_DOMAIN
                path: /
                tls:
                  - secretName: alertmanager-cert
                    hosts:
                      - alertmanager.ARGOCD_ENV_DOMAIN
              config:
                route:
                  receiver: "null"
                  group_wait: 30s
                  group_interval: 5m
                  repeat_interval: 1h
                  group_by: [alertname, severity, id]
                  routes:
                    - receiver: "null"
                      match:
                        severity: null
                      continue: false
                    - receiver: "telegram"
                      match:
                        channels: telegram
                      continue: true
                    - receiver: "info"
                      match:
                        severity: info
                    - receiver: "warning"
                      match:
                        severity: warning
                    - receiver: "critical"
                      match:
                        severity: critical
                receivers:
                  - name: "null"
                  - name: "info"
                    webhook_configs:
                      - url: "http://notification-service.monitoring:8080/alertmanager/room/%21DaMkbMrexCDEDGoiup:hoprnet.io"
                  - name: "warning"
                    webhook_configs:
                      - url: "http://notification-service.monitoring:8080/alertmanager/room/%21WxXYnjzPyglBADfuyc:hoprnet.io"
                  - name: "critical"
                    webhook_configs:
                      - url: "http://notification-service.monitoring:8080/alertmanager/room/%21HgRjXaMRVLzZYZPEFg:hoprnet.io"
                  - name: "telegram"
                    telegram_configs:
                      - chat_id: -1001562396359
                        #bot_token_file: telegram #Enable this in couple versions
                        bot_token: 6201490054:AAEjF_1ahOhmK1ysT2pD9gNRjIjzIwD1JF4
            kubeStateMetrics:
              enabled: true
            nodeExporter:
              enabled: true
            prometheusOperator:
              logLevel: info
            prometheus:
              enabled: true
              ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
                  cert-manager.io/cluster-issuer: production
                hosts:
                  - prometheus.ARGOCD_ENV_DOMAIN
                path: /
                tls:
                  - secretName: prometheus-cert
                    hosts:
                      - prometheus.ARGOCD_ENV_DOMAIN
              prometheusSpec:
                ruleSelectorNilUsesHelmValues: false
                serviceMonitorSelectorNilUsesHelmValues: false
                storageSpec:
                  volumeClaimTemplate:
                    spec:
                      storageClassName: main
                      resources:
                        requests:
                          storage: 100Gi
                ## scrapeConfigs to be selected for target discovery.
                ## If {}, select all scrapeConfigs
                ##
                scrapeConfigSelector: {}
                ## If nil, select own namespace. Namespaces to be selected for scrapeConfig discovery.
                # scrapeConfigNamespaceSelector: {}
                additionalScrapeConfigsSecret:
                  enabled: true
                  name: prometheus-scrape-config
                  key: additional-scrape-configs.yaml
            grafana:
              enabled: true
              adminPassword: ARGOCD_ENV_RANDOM_STRING
              env:
                GF_FEATURE_TOGGLES_ENABLE: publicDashboards
              envFromSecret: grafana
              persistence:
                enabled: true
                storageClassName: main
                size: 1Gi
              additionalDataSources:
                - name: Loki
                  type: loki
                  url: http://loki-read.monitoring:3100
                  isDefault: false
              sidecar:
                dashboards:
                  # If specified, the sidecar will look for annotation with this name to create folder and put graph here.
                  # You can use this parameter together with `provider.foldersFromFilesStructure`to annotate configmaps and create folder structure.
                  folderAnnotation: grafana-dashboard-folder
                  provider:
                    allowUiUpdates: true
                    foldersFromFilesStructure: true
                    disableDeletion: true
              grafana.ini:
                server:
                  root_url: https://grafana.ARGOCD_ENV_DOMAIN
                auth.google:
                  enabled: true
                  allow_sign_up: true
                  auto_login: false
                  scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
                  auth_url: https://accounts.google.com/o/oauth2/auth
                  token_url: https://accounts.google.com/o/oauth2/token
              ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  cert-manager.io/cluster-issuer: production
                hosts:
                  - grafana.ARGOCD_ENV_DOMAIN
                path: /
                tls:
                  - secretName: grafana-cert
                    hosts:
                      - grafana.ARGOCD_ENV_DOMAIN
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
