apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "45.10.1"
    chart: kube-prometheus-stack
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            coreDns:
              enabled: false
            kubeDns:
              enabled: true
            kubeProxy:
              enabled: false
            kubeScheduler:
              enabled: false
            kubeControllerManager:
              enabled: false
            alertmanager:
              enabled: true
              ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
                  cert-manager.io/cluster-issuer: production
                hosts:
                  - alertmanager.ARGOCD_ENV_DOMAIN
                path: /
                tls:
                  - secretName: alertmanager-cert
                    hosts:
                      - alertmanager.ARGOCD_ENV_DOMAIN
              config:
                route:
                  receiver: "null"
                  group_wait: 30s
                  group_interval: 5m
                  repeat_interval: 1h
                  group_by: [alertname, severity, id]
                  routes:
                    - receiver: "null"
                      match:
                        severity: null
                      continue: false
                    - receiver: "telegram"
                      match:
                        channels: telegram
                      continue: true
                    - receiver: "info"
                      match:
                        severity: info
                    - receiver: "warning"
                      match:
                        severity: warning
                    - receiver: "critical"
                      match:
                        severity: critical
                receivers:
                  - name: "null"
                  - name: "info"
                    webhook_configs:
                      - url: "http://notification-service.monitoring:8080/alertmanager/room/%21DaMkbMrexCDEDGoiup:hoprnet.io"
                  - name: "warning"
                    webhook_configs:
                      - url: "http://notification-service.monitoring:8080/alertmanager/room/%21WxXYnjzPyglBADfuyc:hoprnet.io"
                  - name: "critical"
                    webhook_configs:
                      - url: "http://notification-service.monitoring:8080/alertmanager/room/%21HgRjXaMRVLzZYZPEFg:hoprnet.io"
                  - name: "telegram"
                    telegram_configs:
                      - chat_id: -1001562396359
                        #bot_token_file: telegram #Enable this in couple versions
                        bot_token: 6201490054:AAEjF_1ahOhmK1ysT2pD9gNRjIjzIwD1JF4
            kubeStateMetrics:
              enabled: true
            nodeExporter:
              enabled: true
            prometheusOperator:
              logLevel: info
            prometheus:
              enabled: true
              ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
                  cert-manager.io/cluster-issuer: production
                hosts:
                  - prometheus.ARGOCD_ENV_DOMAIN
                path: /
                tls:
                  - secretName: prometheus-cert
                    hosts:
                      - prometheus.ARGOCD_ENV_DOMAIN
              prometheusSpec:
                ruleSelectorNilUsesHelmValues: false
                serviceMonitorSelectorNilUsesHelmValues: false
                storageSpec:
                  volumeClaimTemplate:
                    spec:
                      storageClassName: main
                      resources:
                        requests:
                          storage: 10Gi
                additionalScrapeConfigs:
                  - job_name: hetzner
                    static_configs:
                      - targets:
                          - "78.47.150.194"
                        labels:
                          hostname: "hetzner-staging-alpha-1"
                          ip: "78.47.150.194"
                      - targets:
                          - "91.107.194.8"
                        labels:
                          hostname: "hetzner-staging-alpha-2"
                          ip: "91.107.194.8"
                      - targets:
                          - "159.69.122.70"
                        labels:
                          hostname: "hetzner-staging-alpha-4"
                          ip: "159.69.122.70"
                      - targets:
                          - "49.12.246.83"
                        labels:
                          hostname: "hetzner-staging-alpha-3"
                          ip: "49.12.246.83"
                      - targets:
                          - "142.132.184.57"
                        labels:
                          hostname: "hetzner-staging-alpha-5"
                          ip: "142.132.184.57"
                      - targets:
                          - "128.140.52.34"
                        labels:
                          hostname: "hetzner-staging-alpha-6"
                          ip: "128.140.52.34"
                      - targets:
                          - "116.203.251.244"
                        labels:
                          hostname: "hetzner-staging-alpha-7"
                          ip: "116.203.251.244"
                      - targets:
                          - "49.12.13.222"
                        labels:
                          hostname: "hetzner-staging-alpha-8"
                          ip: "49.12.13.222"
                      - targets:
                          - "49.13.13.52"
                        labels:
                          hostname: "hetzner-staging-alpha-9"
                          ip: "49.13.13.52"
                      - targets:
                          - "49.13.13.55"
                        labels:
                          hostname: "hetzner-staging-alpha-10"
                          ip: "49.13.13.55"
                      - targets:
                          - "91.107.205.15"
                        labels:
                          hostname: "hetzner-staging-alpha-11"
                          ip: "91.107.205.15"
                      - targets:
                          - "49.13.13.104"
                        labels:
                          hostname: "hetzner-staging-alpha-12"
                          ip: "49.13.13.104"
                      - targets:
                          - "49.13.13.114"
                        labels:
                          hostname: "hetzner-staging-alpha-13"
                          ip: "49.13.13.114"
                      - targets:
                          - "49.13.13.117"
                        labels:
                          hostname: "hetzner-staging-alpha-14"
                          ip: "49.13.13.117"
                      - targets:
                          - "49.13.13.106"
                        labels:
                          hostname: "hetzner-staging-alpha-15"
                          ip: "49.13.13.106"
                      - targets:
                          - "95.217.234.91"
                        labels:
                          hostname: "hetzner-staging-alpha-16"
                          ip: "95.217.234.91"
                      - targets:
                          - "65.21.54.172"
                        labels:
                          hostname: "hetzner-staging-alpha-17"
                          ip: "65.21.54.172"
                      - targets:
                          - "135.181.156.126"
                        labels:
                          hostname: "hetzner-staging-alpha-18"
                          ip: "135.181.156.126"
                      - targets:
                          - "135.181.87.129"
                        labels:
                          hostname: "hetzner-staging-alpha-19"
                          ip: "135.181.87.129"
                      - targets:
                          - "135.181.207.234"
                        labels:
                          hostname: "hetzner-staging-alpha-20"
                          ip: "135.181.207.234"
                      - targets:
                          - "37.27.7.199"
                        labels:
                          hostname: "hetzner-staging-alpha-21"
                          ip: "37.27.7.199"
                      - targets:
                          - "135.181.101.184"
                        labels:
                          hostname: "hetzner-staging-alpha-22"
                          ip: "135.181.101.184"
                      - targets:
                          - "95.217.133.151"
                        labels:
                          hostname: "hetzner-staging-alpha-23"
                          ip: "95.217.133.151"
                      - targets:
                          - "95.217.161.46"
                        labels:
                          hostname: "hetzner-staging-alpha-24"
                          ip: "95.217.161.46"
                      - targets:
                          - "37.27.18.179"
                        labels:
                          hostname: "hetzner-staging-alpha-25"
                          ip: "37.27.18.179"
            grafana:
              enabled: true
              adminPassword: ARGOCD_ENV_RANDOM_STRING
              env:
                GF_FEATURE_TOGGLES_ENABLE: publicDashboards
              envFromSecret: grafana
              persistence:
                enabled: true
                storageClassName: main
                size: 1Gi
              additionalDataSources:
                - name: Loki
                  type: loki
                  url: http://loki-read.monitoring:3100
                  isDefault: false
              grafana.ini:
                server:
                  root_url: https://grafana.ARGOCD_ENV_DOMAIN
                auth.google:
                  enabled: true
                  allow_sign_up: true
                  auto_login: false
                  scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
                  auth_url: https://accounts.google.com/o/oauth2/auth
                  token_url: https://accounts.google.com/o/oauth2/token
              ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  cert-manager.io/cluster-issuer: production
                hosts:
                  - grafana.ARGOCD_ENV_DOMAIN
                path: /
                tls:
                  - secretName: grafana-cert
                    hosts:
                      - grafana.ARGOCD_ENV_DOMAIN
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true