apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "45.10.1"
    chart: kube-prometheus-stack
    plugin:
      env:
        - name: HELM_VALUES
          #TODO - grafana adminSecret should be generated on day-1 and not passed to argocd-sugar plugin due to potential security leaks
          value: |
            coreDns:
              enabled: false
            kubeDns:
              enabled: true
            kubeProxy:
              enabled: false
            kubeScheduler:
              enabled: false
            kubeControllerManager:
              enabled: false
            alertmanager:
              enabled: true
              ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
                  cert-manager.io/cluster-issuer: production
                hosts:
                  - alertmanager.ARGOCD_ENV_DOMAIN
                path: /
                tls:
                  - secretName: alertmanager-cert
                    hosts:
                      - alertmanager.ARGOCD_ENV_DOMAIN
              config:
                route:
                  receiver: "null"
                  group_wait: 30s
                  group_interval: 5m
                  repeat_interval: 1h
                  group_by: [alertname, severity, id]
                  routes:
                    - receiver: "null"
                      match:
                        severity: null
                      continue: false
                    - receiver: "telegram"
                      match:
                        channels: telegram
                      continue: true
                    - receiver: "info"
                      match:
                        severity: info
                    - receiver: "warning"
                      match:
                        severity: warning
                    - receiver: "critical"
                      match:
                        severity: critical
                receivers:
                  - name: "null"
                  - name: "info"
                    webhook_configs:
                      - url: "http://notification-service.monitoring:8080/alertmanager/room/%21DaMkbMrexCDEDGoiup:hoprnet.io"
                  - name: "warning"
                    webhook_configs:
                      - url: "http://notification-service.monitoring:8080/alertmanager/room/%21WxXYnjzPyglBADfuyc:hoprnet.io"
                  - name: "critical"
                    webhook_configs:
                      - url: "http://notification-service.monitoring:8080/alertmanager/room/%21HgRjXaMRVLzZYZPEFg:hoprnet.io"
                  - name: "telegram"
                    telegram_configs:
                      - chat_id: -1001562396359
                        #bot_token_file: telegram #Enable this in couple versions
                        bot_token: 6201490054:AAEjF_1ahOhmK1ysT2pD9gNRjIjzIwD1JF4
            kubeStateMetrics:
              enabled: true
            nodeExporter:
              enabled: true
            prometheusOperator:
              logLevel: info
            prometheus:
              enabled: true
              ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
                  cert-manager.io/cluster-issuer: production
                hosts:
                  - prometheus.ARGOCD_ENV_DOMAIN
                path: /
                tls:
                  - secretName: prometheus-cert
                    hosts:
                      - prometheus.ARGOCD_ENV_DOMAIN
              prometheusSpec:
                ruleSelectorNilUsesHelmValues: false
                serviceMonitorSelectorNilUsesHelmValues: false
                storageSpec:
                  volumeClaimTemplate:
                    spec:
                      storageClassName: main
                      resources:
                        requests:
                          storage: 100Gi
                additionalScrapeConfigs:
                  - job_name: hetzner-staging
                    static_configs:
                      - targets:
                          - "78.47.150.194:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-1"
                          job: "hetzner-staging-alpha-1"
                          hoprd_network: monte_rosa
                      - targets:
                          - "91.107.194.8:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-2"
                          job: "hetzner-staging-alpha-2"
                          hoprd_network: monte_rosa
                      - targets:
                          - "49.12.246.83:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-3"
                          job: "hetzner-staging-alpha-3"
                          hoprd_network: monte_rosa
                      - targets:
                          - "159.69.122.70:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-4"
                          job: "hetzner-staging-alpha-4"
                          hoprd_network: monte_rosa
                      - targets:
                          - "142.132.184.57:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-5"
                          job: "hetzner-staging-alpha-5"
                          hoprd_network: monte_rosa
                      - targets:
                          - "128.140.52.34:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-6"
                          job: "hetzner-staging-alpha-6"
                          hoprd_network: monte_rosa
                      - targets:
                          - "116.203.251.244:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-7"
                          job: "hetzner-staging-alpha-7"
                          hoprd_network: monte_rosa
                      - targets:
                          - "49.12.13.222:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-8"
                          job: "hetzner-staging-alpha-8"
                          hoprd_network: monte_rosa
                      - targets:
                          - "49.13.13.52:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-9"
                          job: "hetzner-staging-alpha-9"
                          hoprd_network: monte_rosa
                      - targets:
                          - "49.13.13.55:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-10"
                          job: "hetzner-staging-alpha-10"
                          hoprd_network: monte_rosa
                      - targets:
                          - "91.107.205.15:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-11"
                          job: "hetzner-staging-alpha-11"
                          hoprd_network: monte_rosa
                      - targets:
                          - "49.13.13.104:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-12"
                          job: "hetzner-staging-alpha-12"
                          hoprd_network: monte_rosa
                      - targets:
                          - "49.13.13.114:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-13"
                          job: "hetzner-staging-alpha-13"
                          hoprd_network: monte_rosa
                      - targets:
                          - "49.13.13.117:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-14"
                          job: "hetzner-staging-alpha-14"
                          hoprd_network: monte_rosa
                      - targets:
                          - "49.13.13.106:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-15"
                          job: "hetzner-staging-alpha-15"
                          hoprd_network: monte_rosa
                      - targets:
                          - "95.217.234.91:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-16"
                          job: "hetzner-staging-alpha-16"
                          hoprd_network: monte_rosa
                      - targets:
                          - "65.21.54.172:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-17"
                          job: "hetzner-staging-alpha-17"
                          hoprd_network: monte_rosa
                      - targets:
                          - "135.181.156.126:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-18"
                          job: "hetzner-staging-alpha-18"
                          hoprd_network: monte_rosa
                      - targets:
                          - "135.181.87.129:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-19"
                          job: "hetzner-staging-alpha-19"
                          hoprd_network: monte_rosa
                      - targets:
                          - "135.181.207.234:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-20"
                          job: "hetzner-staging-alpha-20"
                          hoprd_network: monte_rosa
                      - targets:
                          - "37.27.7.199:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-21"
                          job: "hetzner-staging-alpha-21"
                          hoprd_network: monte_rosa
                      - targets:
                          - "135.181.101.184:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-22"
                          job: "hetzner-staging-alpha-22"
                          hoprd_network: monte_rosa
                      - targets:
                          - "95.217.133.151:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-23"
                          job: "hetzner-staging-alpha-23"
                          hoprd_network: monte_rosa
                      - targets:
                          - "95.217.161.46:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-24"
                          job: "hetzner-staging-alpha-24"
                          hoprd_network: monte_rosa
                      - targets:
                          - "37.27.18.179:9100"
                        labels:
                          hostname: "hetzner-staging-alpha-25"
                          job: "hetzner-staging-alpha-25"
                          hoprd_network: monte_rosa
            grafana:
              enabled: true
              adminPassword: ARGOCD_ENV_RANDOM_STRING
              env:
                GF_FEATURE_TOGGLES_ENABLE: publicDashboards
              envFromSecret: grafana
              persistence:
                enabled: true
                storageClassName: main
                size: 1Gi
              additionalDataSources:
                - name: Loki
                  type: loki
                  url: http://loki-read.monitoring:3100
                  isDefault: false
              grafana.ini:
                server:
                  root_url: https://grafana.ARGOCD_ENV_DOMAIN
                auth.google:
                  enabled: true
                  allow_sign_up: true
                  auto_login: false
                  scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
                  auth_url: https://accounts.google.com/o/oauth2/auth
                  token_url: https://accounts.google.com/o/oauth2/token
              ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  cert-manager.io/cluster-issuer: production
                hosts:
                  - grafana.ARGOCD_ENV_DOMAIN
                path: /
                tls:
                  - secretName: grafana-cert
                    hosts:
                      - grafana.ARGOCD_ENV_DOMAIN
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
