{
 "title": "Latency monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(rpch_latencies_success_count, namespace)"
    }
   },
   { "name": "search" }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful count % over selected period",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(rpch_latencies_success_count{namespace=~\"$namespace\"}[${__range_s}s])) / (sum(increase(rpch_latencies_success_count{namespace=~\"$namespace\"}[${__range_s}s])) + sum(increase(rpch_latencies_failure_count{namespace=~\"$namespace\"}[${__range_s}s])))) * 100",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Failed count % over selected period",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(rpch_latencies_failure_count{namespace=~\"$namespace\"}[${__range_s}s])) / (sum(increase(rpch_latencies_success_count{namespace=~\"$namespace\"}[${__range_s}s])) + sum(increase(rpch_latencies_failure_count{namespace=~\"$namespace\"}[${__range_s}s])))) * 100",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Nº routes Staging",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM zero_hop_pairings LIMIT 50 "
    }
   ]
  },
  {
   "title": "Count over the last 60 seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(rpch_latencies_success_count{namespace=~\"$namespace\"}[60s]))",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(increase(rpch_latencies_failure_count{namespace=~\"$namespace\"}[60s]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Nº routes Prod",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM zero_hop_pairings LIMIT 50 "
    }
   ]
  },
  {
   "title": "Successful request latency quantiles (50%, 70%, 90%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rpch_latencies_success{quantile=\"0.5\",namespace=~\"$namespace\"})",
     "legendFormat": "Q50%"
    },
    {
     "expr": "sum(rpch_latencies_success{quantile=\"0.7\",namespace=~\"$namespace\"})",
     "legendFormat": "Q70%"
    },
    {
     "expr": "sum(rpch_latencies_success{quantile=\"0.9\",namespace=~\"$namespace\"})",
     "legendFormat": "Q90%"
    }
   ]
  },
  {
   "title": "Successful request latency quantiles (99%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "sum(rpch_latencies_success{quantile=\"0.99\",namespace=~\"$namespace\"})",
     "legendFormat": "Q99%"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({instance=~\".*latency-monitor\",namespace=~\"$namespace\"} |~ \"$search\"[$__interval]))",
     "legendFormat": "Number of matching logs"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 21 },
   "targets": [
    {
     "expr": "{instance=~\".*latency-monitor\", namespace=~\"$namespace\"} |~ \"$search\""
    },
    {}
   ]
  }
 ]
}
{
 "title": "Availability Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(rpch_latencies_success_count, namespace)"
    }
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Availability of registered nodes",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(peer_id) (availability_monitor_stability{container=\"availability-monitor\",namespace=~\"$namespace\"})",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Availability Monitor logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{container=\"availability-monitor\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "Number of available nodes over time",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (availability_monitor_stability{container=\"availability-monitor\",namespace=~\"$namespace\"})",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Amount of nodes under monitor",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (availability_monitor_stability{container=\"availability-monitor\",namespace=~\"$namespace\"})",
     "legendFormat": "stable"
    },
    {
     "expr": "count (availability_monitor_stability{container=\"availability-monitor\"}) - sum (availability_monitor_stability{container=\"availability-monitor\"})",
     "legendFormat": "unstable"
    }
   ]
  }
 ]
}
{
 "title": "Discovery platform",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Number of successful requests over the last 60 seconds",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (path) (increase(discovery_platform_counter_successful_request[60s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of successful requests over the last 60 seconds",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (path) (increase(discovery_platform_counter_successful_request[60s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(discovery_platform_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Q50%"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(discovery_platform_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Q70%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(discovery_platform_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Q90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(discovery_platform_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Q95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(discovery_platform_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Q99%"
    }
   ]
  },
  {
   "title": "Traefik metrics",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "increase(traefik_service_requests_total{method=\"GET\",service=\"staging-staging-discovery-platform-3020@kubernetes\"}[60s])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Number of requests by clients",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(client) (discovery_platform_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Exit nodes",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(exit_node_counter_provider_request, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of successful provider requests over 70 seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (job) (increase(exit_node_counter_provider_request{status=\"complete\", job=~\"$job\"}[70s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of failed provider requests over 70 seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (job) (increase(exit_node_counter_provider_request{status=\"error\",job=~\"$job\"}[70s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Received", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Number of successful received requests over 70 seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (job) (increase(exit_node_counter_received_request{status=\"complete\", job=~\"$job\"}[70s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of failed received requests over 70 seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (job) (increase(exit_node_counter_received_request{status=\"error\", job=~\"$job\"}[70s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "image",
    "query": {}
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", cluster=\"$cluster\",namespace=\"$namespace\", image_spec=\"$image\"}, pod)"
    }
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Number of logs matching the search phrase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", image=\"$image\", pod=\"$pod\"} |~ \"(?i)$search\"[$__interval]))",
     "legendFormat": "Number of matching logs"
    }
   ]
  },
  {
   "title": "Logs matching the search phrase",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", image=\"$image\", pod=\"$pod\"} |~ \"(?i)$search\""
    }
   ]
  }
 ]
}
{
 "title": "Logs external",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {}
   },
   {
    "name": "container",
    "query": {}
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Logs based on the hostname, container, and search phrase",
   "type": "logs",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{hostname=\"$hostname\", container=\"$container\"} |~ \"(?i)$search\"",
     "maxLines": 1000
    }
   ]
  }
 ]
}
{
 "title": "Logs general",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "query": "label_values(job)" },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$app\"} |~ \"(?i)$search\" [$__interval]))"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{job=\"$app\"} |~ \"(?i)$search\""
    }
   ]
  }
 ]
}