{
 "title": "Hoprd Node",
 "description": "Metrics for Hoprd nodes",
 "tags": [ "hopr" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(core_gauge_num_peers, job)"
    }
   },
   {
    "name": "container",
    "label": "Logs Container",
    "query": {}
   },
   { "name": "search", "label": "Loki Search" }
  ]
 },
 "panels": [
  { "title": "Peers & Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Peers by quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(quality) (core_mgauge_peers_by_quality{job=~\"${pod_name}\"})",
     "legendFormat": "Quality peers - {{quality}} - {{job}}"
    },
    {
     "expr": "sum(core_gauge_num_peers{job=~\"${pod_name}\"}) by (job)",
     "legendFormat": "Total peers - {{job}}"
    }
   ]
  },
  {
   "title": "Relay connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(connect_gauge_relayed_conns{job=~\"${pod_name}\"}) by (job)",
     "legendFormat": "Relayed connections - {{job}}"
    },
    {
     "expr": "sum(connect_gauge_conns_to_relays{job=~\"${pod_name}\"}) by (job)",
     "legendFormat": "Connected relays - {{job}}"
    }
   ]
  },
  {
   "title": "Network health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(core_gauge_network_health{job=~\"${pod_name}\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pings per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(rate(core_counter_heartbeat_successful_pings{job=~\"${pod_name}\"}[1m])) by (job)",
     "legendFormat": "Successful - {{job}}"
    },
    {
     "expr": "avg(rate(core_counter_heartbeat_failed_pings{job=~\"${pod_name}\"}[1m])) by (job)",
     "legendFormat": "Failed - {{job}}"
    }
   ]
  },
  {
   "title": "Total heartbeat probing time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(core_histogram_heartbeat_time_seconds_bucket{job=~\"${pod_name}\"})  by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Ping response time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(core_histogram_ping_time_seconds_bucket{job=~\"${pod_name}\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Network metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Message statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_counter_received_messages{job=~\"${pod_name}\"})",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(core_counter_sent_messages{job=~\"${pod_name}\"})",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(core_counter_forwarded_messages{job=~\"${pod_name}\"})",
     "legendFormat": "Forwarded"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_gauge_num_incoming_channels{job=~\"${pod_name}\"})",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(core_gauge_num_outgoing_channels{job=~\"${pod_name}\"})",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Hourly message rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "avg(rate(core_counter_received_messages{job=~\"${pod_name}\"}[1h])) by (job)",
     "legendFormat": "Received - {{job}}"
    },
    {
     "expr": "avg(rate(core_counter_sent_messages{job=~\"${pod_name}\"}[1h])) by (job)",
     "legendFormat": "Sent - {{job}}"
    },
    {
     "expr": "avg(rate(core_counter_forwarded_messages{job=~\"${pod_name}\"}[1h])) by (job)",
     "legendFormat": "Forwarded - {{job}}"
    }
   ]
  },
  {
   "title": "Winning Tickets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_ethereum_counter_winning_tickets{job=~\"${pod_name}\"})",
     "legendFormat": "Winning tickets"
    },
    {
     "expr": "sum(core_counter_losing_tickets{job=\"${pod_name}\"})",
     "legendFormat": "Losing tickets"
    }
   ]
  },
  { "title": "V8 metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Bytes of used heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(hoprd_gauge_nodejs_total_used_heap_bytes{job=~\"${pod_name}\"}) by (job)",
     "legendFormat": "Used heap - {{job}}"
    },
    {
     "expr": "avg(avg_over_time(hoprd_gauge_nodejs_total_used_heap_bytes{job=~\"${pod_name}\"}[1h])) by (job)",
     "legendFormat": "Used heap (moving avg over 1h) - {{job}}"
    }
   ]
  },
  {
   "title": "Number of restarts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(hoprd_gauge_startup_unix_time_seconds{job=~\"${pod_name}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes of total available heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(hoprd_gauge_nodejs_total_available_heap_bytes{job=~\"${pod_name}\"}) by (job)",
     "legendFormat": "Total available heap - {{job}}"
    },
    {
     "expr": "avg(avg_over_time(hoprd_gauge_nodejs_total_available_heap_bytes{job=~\"${pod_name}\"}[1h])) by (job)",
     "legendFormat": "Total available heap (moving avg over 1h) - {{job}}"
    }
   ]
  },
  {
   "title": "Startup timestamp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum(hoprd_gauge_startup_unix_time_seconds{job=~\"${pod_name}\"}) by (job)",
     "legendFormat": "Startup - {{job}}"
    }
   ]
  },
  {
   "title": "Node Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "{node_name=~\"$pod_name\", container=\"$container\"}  |~ \"(?i)$search\""
    }
   ]
  }
 ]
}
{
 "title": "Hoprd Network",
 "description": "Basic metrics overview of HOPR nodes",
 "tags": [ "hopr" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(core_gauge_num_peers, hoprd_network)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network connectivity health",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(core_gauge_network_health{hoprd_network=\"${network}\"}) by (job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of restarts",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(changes(hoprd_gauge_startup_unix_time_seconds{hoprd_network=\"${network}\"}[30m])) by (job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of high quality peers per instance",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(job) (core_mgauge_peers_by_quality{hoprd_network=\"${network}\",quality=\"high\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}