apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forward-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: "2.2.2"
    chart: traefik-forward-auth
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            env:
              TZ: UTC
              URL_PATH: /_oauth
              DEFAULT_PROVIDER: google
              LOG_LEVEL: debug
              SECRET:
                valueFrom:
                  secretKeyRef:
                    name: forward-auth
                    key: traefik-forward-auth-secret
              PROVIDERS_GOOGLE_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: forward-auth
                    key: traefik-forward-auth-google-client-id
              PROVIDERS_GOOGLE_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: forward-auth
                    key: traefik-forward-auth-google-client-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
