apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: "v1.11.0"
    chart: cert-manager
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            installCRDs: true
            serviceAccount:
              annotations:
                iam.gke.io/gcp-service-account: ARGOCD_ENV_CLUSTER_NAME-cert-manager@ARGOCD_ENV_GOOGLE_PROJECT.iam.gserviceaccount.com
            securityContext:
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            containerSecurityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 256Mi
            prometheus:
              enabled: true
              servicemonitor:
                enabled: true
            webhook:
              networkPolicy:
                enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
