apiVersion: v1
kind: ResourceQuota
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  hard:
    #Remember to give enough resources for rolling release
    requests.cpu: "20m"
    requests.memory: 512Mi
    requests.storage: 10Gi
    limits.cpu: "20m"
    limits.memory: 512Mi