apiVersion: v1
kind: ResourceQuota
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  hard:
    requests.cpu: "10m"
    requests.memory: 256Mi
    requests.storage: 10Gi
    limits.cpu: "10m"
    limits.memory: 256Mi