{
 "title": "Hoprd Network",
 "description": "Basic metrics overview of HOPR nodes",
 "tags": [ "hopr" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(core_gauge_num_peers, hoprd_network)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network connectivity health",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(core_gauge_network_health{hoprd_network=\"${network}\"}) by (job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of restarts",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(changes(hoprd_gauge_startup_unix_time_seconds{hoprd_network=\"${network}\"}[30m])) by (job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of high quality peers per instance",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(job) (core_mgauge_peers_by_quality{hoprd_network=\"${network}\",quality=\"high\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}