apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    GF_AUTH_GOOGLE_CLIENT_ID: AgBT27XVRoZ5+ro6iInVAVRGR4uV2goEkTj3pVZYOr7UZiLtKCebGTeCPUFqYgWaOrlvWehtOtX8gXPKsFStt0grbWd+Hkjv01lqaPRRs+8S5tHnJNMdvp/JfejG9/wrnnxD/BJ+DU2mn4d7cpxKHgJvs/aiNHxSotgPqcfieCop4XWKM+atzhYb5kBzSdO0eB02Antonl+87yEm5B/zQZ0Jlo9aHm8sylmjsPkG9aKIydrmdchyztWVMilf1HbWP0fPJDb1Ull/qIDLxaWQ81kwQT97fkzv9Q6GtGSN4KUhZquHP4mUkrOIKQ78UxJAmpd/9zM1djksAfYo2Bt07EUVzbSHJAcboO6509qy6P520JAoPWeSLqL9FnLFflSBYaFdEq+KfyEkQSW6oaPyIXf+JuUk50V8B49mAhFDyT1KxLLwlFLAz7aPcVodlNyDlGXVLshEPCEUgZam3RzA9DMDKZDfkWYUeWdr/D3TDX8UT/2doN0b2iwSYH3Uuk1O5OU174UVhtNFM7yWcI2WwRdKEK4MQrXM1d7YyucGD6umrVkF2U09O+W4sGZEf7wj5oRLtALks/kPU1yGy0p81SDPyYXSnnBzxsBwYekHPL/wC7mKVZR2CkrmGiIhIV9D3VjDlWnRyo3UDVAoe1Lzgh/tQblUb4VS4YE1stvMIUkQLidCYtLKBNngSPt6xu+gBG3f3Rveaxi57U6gMZ3mzNCgTTxX6WfSZ6ahEXy3gXm7yUshKFE00ts6+hH+F0AOAbnS2iDd8fUzPC46MI7D6ILSGrgUozkgZhM=
    GF_AUTH_GOOGLE_CLIENT_SECRET: AgCf7MtbfOHcF3yrGqlYL2vfDflWqJuA9xcZZz9N72jFpngLbI+QssYDr5A6PGEK3PK6Tkqe6Ot+iO4WBi57QTFzM3SgHpPWycCDXmHfdg8WoM14vazDL1nQc4PPF77Z8pZMYBcjc2lml9AOjFyQzJB5/vRjm40PlikhHchTpV8Oepj+nKlZKtJjsbayM5t9AtdK6+n4/ydbeGPyzgS4ZxCuIP1U3VmUkKpYduGSQcAQybMSV4s7BMHGyywikv/D1RjiPVJuFsk/05D2khnzVMe3VZsMXVkoK3KctHqou/8T6y9j9cC+GjiMXkZ3Hq134clX7awFoKLjclNCBV8Q3pWAIOv/X5C+S6HqPvlxP0fN+QsTCUpeLugMAeFxi85/baorR+1aIzQmYjJc9ub0kblpmNRTZ7J+BDxZu1kMx8r6cwzIlpLc7MNXLzHv/F8G28TB0IWmpHE6+5gZpbnujbC9Xgwz8bI1IZNXNhxAjm3bfN07gydPHN4wexoTwTYXoEpbNZBkf8LgGbLmtXzQ7UaPTj6fTaTWxzU/HkHXtrFsg0U73qOQZdClb3nddb6ys2smNI/RXMvLOppSmm6foDMSD7BUdDLqdL2+YOT9Z+FF/Woq0nmFv/x2nsOtZHXKp8oC0dYFxoj+j3QtuRjyo2JJuQRk/PQlLJN/QDph4D3Twahq10kW6at7xQlyvHK0GMUbUF1OTaV89H0K0CZrD8bS8TGOlHcDnZvHd9Ygm2BCWmvWZA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque