apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rate-limiting
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  rateLimit:
    average: 10
    burst: 5