apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
  namespace: authelia
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forwardAuth:
    address: "http://authelia.authelia/api/verify?rd=https://authelia.ARGOCD_ENV_DOMAIN"
    trustForwardHeader: true
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Name"
      - "Remote-Email"
      - "Remote-Groups"